# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Musify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Musify
  pod 'Spotify'
  target 'MusifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MusifyUITests' do
    # Pods for testing
  end

end
